# Trim a stream
# This command will trim an input stream. Trimming will be fast, as no
# re-encoding takes place. It will, however, not be frame accurate.
profile.trim.work.name = trim track
profile.trim.work.input = stream
profile.trim.work.output = visual
profile.trim.work.suffix = -trimmed.#{in.video.suffix}
profile.trim.work.ffmpeg.command = -ss #{trim.start} -i #{in.video.path} -t #{trim.duration} -c copy #{out.dir}/#{out.name}#{out.suffix}

# Concat - lossless concat
# Source files must be of the same dimension and codecs and they will be used in the target
# It uses ffmpeg concat demuxer
# command line is "ffmpeg -f concat -safe 0 -i mylist.txt -c copy output"
# where mylist.txt contains one line per file for each track: file '<full pathname>'
profile.concat-samecodec.work.name = concat-samecodec
profile.concat-samecodec.work.input = visual
profile.concat-samecodec.work.output = visual
profile.concat-samecodec.work.suffix = -concatenated.#{in.video.suffix}
profile.concat-samecodec.work.ffmpeg.command = #{concatCommand} -c copy #{out.dir}/#{out.name}#{out.suffix}

# Editor
# This profile is used as a preview and work copy for the video editor.
# The gnonlin component in the gstreamer based video editor modules needs
# an mp4 codec to work reliable. This could also be used for the web preview
# although the file might be quite large for web distribution
profile.editor.work.name = editor
profile.editor.work.input = audiovisual
profile.editor.work.output = audiovisual
profile.editor.work.suffix = -editor.mp4
profile.editor.work.mimetype = video/mp4
profile.editor.work.ffmpeg.command = -i #{in.video.path} -shortest -c:v libx264 -preset superfast -pix_fmt yuv420p -crf 18 -c:a aac -strict -2 -b:a 196k #{out.dir}/#{out.name}#{out.suffix}

# Generate silent audio tracks for filling gaps for partial import operation
profile.import.silent.name = Generate silent audio tracks for filling gaps
profile.import.silent.input = nothing
profile.import.silent.output = audio
profile.import.silent.suffix = -silent-audio.mp4
profile.import.silent.ffmpeg.command = -strict -2 -filter_complex aevalsrc=0:d=#{time} -c:a aac -b:a 8k -ar 44100 #{out.dir}/#{out.name}#{out.suffix}

# Extract last image for partial import operation
profile.import.image-frame.name = Extract last image
profile.import.image-frame.input = visual
profile.import.image-frame.output = image
profile.import.image-frame.suffix = -image.jpg
profile.import.image-frame.ffmpeg.command = -sseof -3 -i #{in.video.path} -update 1 -q:v 1 #{out.dir}/#{out.name}#{out.suffix}

# Extract image for partial import operation
profile.import.preview.name = Extract an image
profile.import.preview.input = visual
profile.import.preview.output = image
profile.import.preview.suffix = -image.jpg
profile.import.preview.ffmpeg.command = -ss #{time} -i #{in.video.path} -r 1 -frames:v 1 #{out.dir}/#{out.name}#{out.suffix}

# Used by Partial Import operation to encode tracks into equal formats
profile.encode.partial-import.name = editor
profile.encode.partial-import.input = audiovisual
profile.encode.partial-import.output = audiovisual
profile.encode.partial-import.suffix = -editor.mp4
profile.encode.partial-import.mimetype = video/mp4
profile.encode.partial-import.ffmpeg.command = -i #{in.video.path} \
  -filter:v crop=trunc(iw/2)*2:trunc(ih/2)*2,fps=25 -shortest -c:v libx264 -preset superfast -pix_fmt yuv420p -crf 18 -c:a aac -b:a 196k \
  #{out.dir}/#{out.name}#{out.suffix}

# Preencode
#   Used by partial import to make all videos have the same resolution,
#   codec, framerate and samplerate to allow for usage of the concat
#   demuxer.
#   MUST specify the same framerate as image-movie.work
profile.partial-import-preencode.name = partial-import-preencode
profile.partial-import-preencode.input = audiovisual
profile.partial-import-preencode.output = audiovisual
profile.partial-import-preencode.suffix = -preencoded.mp4
profile.partial-import-preencode.mimetype = video/mp4
profile.partial-import-preencode.ffmpeg.command = -i #{in.video.path} \
  -filter:v scale=1920:-2,fps=30 \
  -shortest -c:v libx264 -pix_fmt yuv420p \
  -c:a aac -b:a 196k \
  -ar 44100 -max_muxing_queue_size 9999 \
  #{out.dir}/#{out.name}#{out.suffix}

#Thumbnail section
# Downscale thumbnail preview image for video editor
profile.editor.thumbnail.preview.downscale.name = Downscale thumbnail preview image for video editor
profile.editor.thumbnail.preview.downscale.input = visual
profile.editor.thumbnail.preview.downscale.output = image
profile.editor.thumbnail.preview.downscale.suffix = -small.jpg
profile.editor.thumbnail.preview.downscale.ffmpeg.command = -i #{in.video.path} -r 1 -frames:v 1 -filter:v yadif,scale=320:-1 #{out.dir}/#{out.name}#{out.suffix}

# Extract thumbnail preview image for video editor
profile.editor.thumbnail.preview.name = Thumbnail preview image for video editor
profile.editor.thumbnail.preview.input = visual
profile.editor.thumbnail.preview.output = image
profile.editor.thumbnail.preview.suffix = -preview.jpg
profile.editor.thumbnail.preview.ffmpeg.command = -ss #{time} -i #{in.video.path} -r 1 -frames:v 1 -filter:v yadif,scale=320:-1 #{out.dir}/#{out.name}#{out.suffix}

# Extract thumbnail master image for video editor
profile.editor.thumbnail.master.name = Thumbnail master image
profile.editor.thumbnail.master.input = visual
profile.editor.thumbnail.master.output = image
profile.editor.thumbnail.master.suffix = -master.jpg
profile.editor.thumbnail.master.ffmpeg.command = -ss #{time} -i #{in.video.path} -r 1 -frames:v 1 #{out.dir}/#{out.name}#{out.suffix}
