profile.studio.adaptive-parallel.http.name = parallel encoding of studio video in multiple qualities for adaptive streaming
profile.studio.adaptive-parallel.http.input = visual
profile.studio.adaptive-parallel.http.output = visual
profile.studio.adaptive-parallel.http.suffix.2160p-quality = -2160p-quality.mp4
profile.studio.adaptive-parallel.http.suffix.1440p-quality = -1440p-quality.mp4
profile.studio.adaptive-parallel.http.suffix.1080p-quality = -1080p-quality.mp4
profile.studio.adaptive-parallel.http.suffix.720p-quality = -720p-quality.mp4
profile.studio.adaptive-parallel.http.suffix.360p-quality = -360p-quality.mp4
profile.studio.adaptive-parallel.http.jobload = 4
profile.studio.adaptive-parallel.http.ffmpeg.command.if-height-geq-1800 = \
  -filter:v scale=w=3840:h=trunc(3840/dar/2)*2,setsar=1,fps=25 \
    -c:v libx264 -tune film -pix_fmt yuv420p \
    -x264opts keyint=25:min-keyint=25:no-scenecut -maxrate 14800k -bufsize 14800k \
    -c:a aac -b:a 128k -ac 2 \
    -movflags +faststart #{out.dir}/#{out.name}#{out.suffix.2160p-quality}
profile.studio.adaptive-parallel.http.ffmpeg.command.if-height-geq-1260 = \
  -filter:v scale=w=2560:h=trunc(2560/dar/2)*2,setsar=1,fps=25 \
    -c:v libx264 -tune film -pix_fmt yuv420p \
    -x264opts keyint=25:min-keyint=25:no-scenecut -maxrate 9800k -bufsize 9800k \
    -c:a aac -b:a 128k -ac 2 \
    -movflags +faststart #{out.dir}/#{out.name}#{out.suffix.1440p-quality}
profile.studio.adaptive-parallel.http.ffmpeg.command.if-height-geq-900 = \
  -filter:v scale=w=1920:h=trunc(1920/dar/2)*2,setsar=1,fps=25 \
    -c:v libx264 -tune film -pix_fmt yuv420p \
    -x264opts keyint=25:min-keyint=25:no-scenecut -maxrate 4800k -bufsize 4800k \
    -c:a aac -b:a 128k -ac 2 \
    -movflags +faststart #{out.dir}/#{out.name}#{out.suffix.1080p-quality}
profile.studio.adaptive-parallel.http.ffmpeg.command = -i #{in.video.path} \
  #{if-height-geq-1800} \
  #{if-height-geq-1260} \
  #{if-height-geq-900} \
  -filter:v scale=w=1280:h=trunc(1280/dar/2)*2,setsar=1,fps=25 \
    -c:v libx264 -tune film -pix_fmt yuv420p \
    -x264opts keyint=25:min-keyint=25:no-scenecut -maxrate 2400k -bufsize 2400k \
    -c:a aac -b:a 128k -ac 2 \
    -movflags +faststart #{out.dir}/#{out.name}#{out.suffix.720p-quality} \
  -filter:v scale=w=640:h=trunc(640/dar/2)*2,setsar=1,fps=25 \
    -c:v libx264 -tune film -pix_fmt yuv420p \
    -x264opts keyint=25:min-keyint=25:no-scenecut -maxrate 1200k -bufsize 1200k \
    -c:a aac -b:a 128k -ac 2 \
    -movflags +faststart #{out.dir}/#{out.name}#{out.suffix.360p-quality}
